[project]
name = "mongodb-mgr-sdk-mcp-server"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "mcp[cli]",
    "volcengine-python-sdk",
]
